spring:
  datasource:
    url: jdbc:mysql://localhost:3306/photoappdb
    username: root
    password: root07!!
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true

tokenSecret: secret

server:
  servlet:
    context-path: /mobile-app-ws
